general.import = [
  # uncomment the flavour you want below:
 "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
dimensions = { columns = 100, lines = 40 }
#startup_mode = "Maximized" # Maximized window
dynamic_title = true

[font]
size = 13
